# This manages a long-running data migration on the API servers.
# 
# Migration: data:20210605_fill_version_headers_from_source_metadata[force,start_date,end_date]
# Description: Moves version headers from `source_metadata.headers` to a new
# top-level `headers` field.
apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrate-version-headers-job
  namespace: staging
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: api-migrate-version-headers-job
        image: envirodgi/db-status-update-job:69802f857b354eda800a3d2ca55287a78241fde3
        command: ["bundle", "exec", "rake", "data:20210605_fill_version_headers_from_source_metadata"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1500m"
        env:
        - name: ALLOWED_ARCHIVE_HOSTS
          value: "https://edgi-wm-versionista.s3.amazonaws.com/ https://edgi-wm-versionista.s3-us-west-2.amazonaws.com/ https://edgi-versionista-archive.s3.amazonaws.com/ https://edgi-wm-archive.s3.amazonaws.com/ https://edgi-wm-archive.s3.us-west-2.amazonaws.com/"
        - name: AUTO_ANNOTATION_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auto_annotation_user
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws_access_key_id
        - name: AWS_ARCHIVE_BUCKET
          value: edgi-wm-archive
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws_secret_access_key
        - name: AWS_WORKING_BUCKET
          value: edgi-wm-db-internal
        - name: CACHE_DATE_DIFFER
          value: "2019-09-22T00:00:00Z"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_rds
        - name: DIFFER_DEFAULT
          value: http://diffing:80
        - name: HOST_URL
          value: "https://api-staging.monitoring.envirodatagov.org/"
        - name: LANG
          value: en_US.UTF-8
        - name: MAIL_SENDER
          value: website.monitoring@envirodatagov.org
        - name: MAX_COLLECTION_PAGE_SIZE
          value: "1000"
        - name: NEW_RELIC_AGENT_ENABLED
          value: "false"
        - name: POSTMARK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postmark_api_token
        - name: RACK_ENV
          value: production
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: enabled
        - name: RAILS_SERVE_STATIC_FILES
          value: enabled
        - name: REDIS_URL
          value: redis://redis-master:6379
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key_base
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sentry_dsn
        - name: TOKEN_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: token_private_key
        - name: INCREMENTAL_UPDATE
          value: "1"
