apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-worker
  namespace: production
spec:
  selector:
    matchLabels:
      app: import-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: import-worker
    spec:
      containers:
      - name: db-import-worker
        image: envirodgi/db-import-worker:7cbeea0571a0751fa44f890cfd2d2ab61a8c157a
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1500m"
        env:
        - name: ALLOWED_ARCHIVE_HOSTS
          value: "https://edgi-wm-versionista.s3.amazonaws.com/ https://edgi-wm-versionista.s3-us-west-2.amazonaws.com/ https://edgi-wm-archive.s3.amazonaws.com/ https://edgi-wm-archive.s3.us-west-2.amazonaws.com/"
        # Set to "true" to be safe/conservative on what kinds of diffs to try
        # If we suddenly see the diff server going nuts, maybe uncomment this.
        # - name: ANALYSIS_REQUIRE_MEDIA_TYPE
        #   value: "true"
        - name: AUTO_ANNOTATION_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: auto_annotation_user
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws_access_key_id
        - name: AWS_ARCHIVE_BUCKET
          value: edgi-wm-archive
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws_secret_access_key
        - name: AWS_WORKING_BUCKET
          value: edgi-wm-db-internal
        - name: CACHE_DATE_DIFFER
          value: "2019-09-22T00:00:00Z"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_rds
        - name: DIFFER_DEFAULT
          value: http://diffing:80
        - name: HOST_URL
          value: "https://api.monitoring.envirodatagov.org/"
        - name: LANG
          value: en_US.UTF-8
        - name: MAIL_SENDER
          value: website.monitoring@envirodatagov.org
        - name: MAX_COLLECTION_PAGE_SIZE
          value: "1000"
        - name: NEW_RELIC_AGENT_ENABLED
          value: "false"
        - name: POSTMARK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postmark_api_token
        - name: QUEUES
          value: "mailers,import,analysis"
        - name: RACK_ENV
          value: production
        - name: RAILS_ENV
          value: production
        - name: RAILS_SERVE_STATIC_FILES
          value: enabled
        # Redis cache is disabled in favor of just relying on CloudFront.
        # - name: REDIS_CACHE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: redis_cache_url
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key_base
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sentry_dsn
        - name: TOKEN_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: token_private_key
        - name: API_READ_ONLY
          value: "false"
        - name: INCREMENTAL_UPDATE
          value: "6"
